reduce pipeline for testing and push trivy summary to github action step summary

diff --git a/.github/workflows/pull-request-path.yml b/.github/workflows/pull-request-path.yml
--- a/.github/workflows/pull-request-path.yml
+++ b/.github/workflows/pull-request-path.yml
@@ -163,177 +163,177 @@ jobs:
       (needs.node_build.result == 'success' || needs.node_build.result == 'skipped') &&
       needs.workflow_variables.result == 'success'
 
-  code_coverage:
-    name: upload to code coverage
-    uses: ./.github/workflows/_codecov.yml
-    with:
-      specific_path: ${{ needs.workflow_variables.outputs.specific_path }}
-    needs:
-      - docker_build_scan_push
-      - workflow_variables
-    secrets: inherit
-    if: |
-      always() &&
-      ( needs.docker_build_scan_push.result == 'success' || needs.docker_build_scan_push.result == 'failure' )
+  # code_coverage:
+  #   name: upload to code coverage
+  #   uses: ./.github/workflows/_codecov.yml
+  #   with:
+  #     specific_path: ${{ needs.workflow_variables.outputs.specific_path }}
+  #   needs:
+  #     - docker_build_scan_push
+  #     - workflow_variables
+  #   secrets: inherit
+  #   if: |
+  #     always() &&
+  #     ( needs.docker_build_scan_push.result == 'success' || needs.docker_build_scan_push.result == 'failure' )
 
-  terraform_apply_shared_development:
-    name: terraform apply shared development
-    uses: ./.github/workflows/_run-terraform.yml
-    needs:
-      - terraform_lint
-      - workflow_variables
-    with:
-      workspace: development
-      terraform_path: account
-      specific_path: ${{ needs.workflow_variables.outputs.specific_path }}
-      apply: false
-    secrets: inherit
-    if: |
-      always() &&
-      needs.terraform_lint.result == 'success'
+  # terraform_apply_shared_development:
+  #   name: terraform apply shared development
+  #   uses: ./.github/workflows/_run-terraform.yml
+  #   needs:
+  #     - terraform_lint
+  #     - workflow_variables
+  #   with:
+  #     workspace: development
+  #     terraform_path: account
+  #     specific_path: ${{ needs.workflow_variables.outputs.specific_path }}
+  #     apply: false
+  #   secrets: inherit
+  #   if: |
+  #     always() &&
+  #     needs.terraform_lint.result == 'success'
 
-  terraform_apply_environment:
-    name: terraform apply environment
-    uses: ./.github/workflows/_run-terraform.yml
-    needs:
-      - docker_build_scan_push
-      - terraform_lint
-      - workflow_variables
-    with:
-      workspace: ${{ needs.workflow_variables.outputs.workspace_name }}
-      terraform_path: environment
-      container_version: ${{ needs.workflow_variables.outputs.safe_branch_name }}-${{ needs.workflow_variables.outputs.short_sha }}
-      apply: true
-      specific_path: ${{ needs.workflow_variables.outputs.specific_path }}
-      add_ttl: true
-    secrets: inherit
-    if: |
-      always() &&
-      needs.terraform_lint.result == 'success' &&
-      needs.docker_build_scan_push.result == 'success' &&
-      needs.workflow_variables.result == 'success'
+  # terraform_apply_environment:
+  #   name: terraform apply environment
+  #   uses: ./.github/workflows/_run-terraform.yml
+  #   needs:
+  #     - docker_build_scan_push
+  #     - terraform_lint
+  #     - workflow_variables
+  #   with:
+  #     workspace: ${{ needs.workflow_variables.outputs.workspace_name }}
+  #     terraform_path: environment
+  #     container_version: ${{ needs.workflow_variables.outputs.safe_branch_name }}-${{ needs.workflow_variables.outputs.short_sha }}
+  #     apply: true
+  #     specific_path: ${{ needs.workflow_variables.outputs.specific_path }}
+  #     add_ttl: true
+  #   secrets: inherit
+  #   if: |
+  #     always() &&
+  #     needs.terraform_lint.result == 'success' &&
+  #     needs.docker_build_scan_push.result == 'success' &&
+  #     needs.workflow_variables.result == 'success'
 
-  terraform_preproduction_plan_environment:
-    name: terraform plan preproduction environment
-    uses: ./.github/workflows/_run-terraform.yml
-    needs:
-      - docker_build_scan_push
-      - terraform_lint
-      - workflow_variables
-    with:
-      workspace: preproduction
-      terraform_path: environment
-      container_version: main-${{ needs.workflow_variables.outputs.short_sha }}
-      apply: false
-      specific_path: all
-      add_ttl: false
-    secrets: inherit
-    if: |
-      always() &&
-      needs.terraform_lint.result == 'success' &&
-      needs.docker_build_scan_push.result == 'success' &&
-      needs.workflow_variables.result == 'success'
+  # terraform_preproduction_plan_environment:
+  #   name: terraform plan preproduction environment
+  #   uses: ./.github/workflows/_run-terraform.yml
+  #   needs:
+  #     - docker_build_scan_push
+  #     - terraform_lint
+  #     - workflow_variables
+  #   with:
+  #     workspace: preproduction
+  #     terraform_path: environment
+  #     container_version: main-${{ needs.workflow_variables.outputs.short_sha }}
+  #     apply: false
+  #     specific_path: all
+  #     add_ttl: false
+  #   secrets: inherit
+  #   if: |
+  #     always() &&
+  #     needs.terraform_lint.result == 'success' &&
+  #     needs.docker_build_scan_push.result == 'success' &&
+  #     needs.workflow_variables.result == 'success'
 
-  seed_dynamodb:
-    name: seed dynamodb
-    uses: ./.github/workflows/_seed-database.yml
-    needs:
-      - terraform_apply_environment
-      - terraform_apply_shared_development
-      - workflow_variables
-    with:
-      workspace: ${{ needs.workflow_variables.outputs.workspace_name }}
-    secrets: inherit
-    if: |
-      always() &&
-      needs.terraform_apply_environment.result == 'success' &&
-      needs.terraform_apply_shared_development.result == 'success'
+  # seed_dynamodb:
+  #   name: seed dynamodb
+  #   uses: ./.github/workflows/_seed-database.yml
+  #   needs:
+  #     - terraform_apply_environment
+  #     - terraform_apply_shared_development
+  #     - workflow_variables
+  #   with:
+  #     workspace: ${{ needs.workflow_variables.outputs.workspace_name }}
+  #   secrets: inherit
+  #   if: |
+  #     always() &&
+  #     needs.terraform_apply_environment.result == 'success' &&
+  #     needs.terraform_apply_shared_development.result == 'success'
 
-  run_behat_suite:
-    name: run behat tests against environment
-    uses: ./.github/workflows/_run-behat-tests.yml
-    needs:
-      - seed_dynamodb
-      - workflow_variables
-    with:
-      workspace: ${{ needs.workflow_variables.outputs.workspace_name }}
-    secrets: inherit
-    if: |
-      always() &&
-      needs.workflow_variables.result == 'success' &&
-      needs.seed_dynamodb.result == 'success'
+  # run_behat_suite:
+  #   name: run behat tests against environment
+  #   uses: ./.github/workflows/_run-behat-tests.yml
+  #   needs:
+  #     - seed_dynamodb
+  #     - workflow_variables
+  #   with:
+  #     workspace: ${{ needs.workflow_variables.outputs.workspace_name }}
+  #   secrets: inherit
+  #   if: |
+  #     always() &&
+  #     needs.workflow_variables.result == 'success' &&
+  #     needs.seed_dynamodb.result == 'success'
 
-  slack_notify:
-    name: notify of result
-    uses: ./.github/workflows/_slack-notification.yml
-    needs:
-      - run_behat_suite
-      - workflow_variables
-    with:
-      template: successful_dev_build.txt
-      workflow_status: ${{ needs.run_behat_suite.result }}
-      workspace: ${{ needs.workflow_variables.outputs.workspace_name }}
-    secrets:
-      webhook: ${{ secrets.DEV_SLACK_WEB_HOOK }}
-    if: |
-      always() &&
-      needs.run_behat_suite.result == 'success'
+  # slack_notify:
+  #   name: notify of result
+  #   uses: ./.github/workflows/_slack-notification.yml
+  #   needs:
+  #     - run_behat_suite
+  #     - workflow_variables
+  #   with:
+  #     template: successful_dev_build.txt
+  #     workflow_status: ${{ needs.run_behat_suite.result }}
+  #     workspace: ${{ needs.workflow_variables.outputs.workspace_name }}
+  #   secrets:
+  #     webhook: ${{ secrets.DEV_SLACK_WEB_HOOK }}
+  #   if: |
+  #     always() &&
+  #     needs.run_behat_suite.result == 'success'
 
-  # Required end of workflow job
-  end_of_workflow:
-    name: end of workflow
-    runs-on: ubuntu-latest
-    needs:
-      - workflow_variables
-      - update_documentation
-      - docker_build_scan_push
-      - run_behat_suite
-      - terraform_preproduction_plan_environment
-    steps:
-      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+  # # Required end of workflow job
+  # end_of_workflow:
+  #   name: end of workflow
+  #   runs-on: ubuntu-latest
+  #   needs:
+  #     - workflow_variables
+  #     - update_documentation
+  #     - docker_build_scan_push
+  #     - run_behat_suite
+  #     - terraform_preproduction_plan_environment
+  #   steps:
+  #     - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
 
-      - name: Calculate Step Duration
-        id: calculate_durations
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        run: |
-          python ./scripts/pipeline/output_step_timing/step_timing.py -json '{
-            "test node dependencies / unit-test": ["run tests with jest"],
-            "build, test, scan and push / docker_build_scan_push": ["docker unit tests", "docker integration and acceptance tests"],
-            "run behat tests against environment / build-web": ["run behat test suite"]
-          }'
+  #     - name: Calculate Step Duration
+  #       id: calculate_durations
+  #       env:
+  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  #       run: |
+  #         python ./scripts/pipeline/output_step_timing/step_timing.py -json '{
+  #           "test node dependencies / unit-test": ["run tests with jest"],
+  #           "build, test, scan and push / docker_build_scan_push": ["docker unit tests", "docker integration and acceptance tests"],
+  #           "run behat tests against environment / build-web": ["run behat test suite"]
+  #         }'
 
-      - name: Create a table with job durations and set as output
-        id: create_table
-        run: |
-          {
-            echo ${{ needs.docker_build_scan_push.outputs.matrix_job_names }}
-            echo "| Job | Step | Duration |"
-            echo "| --- | --- | --- |"
-            jobs=$(echo '${{ steps.calculate_durations.outputs.jobs }}' | jq -r '.[]')
-            steps=$(echo '${{ steps.calculate_durations.outputs.steps }}' | jq -r '.[]')
-            durations=$(echo '${{ steps.calculate_durations.outputs.durations }}' | jq -r '.[]')
-            for i in $(seq 0 $(($(echo "$jobs" | wc -l) - 1))); do
-              job=$(echo "$jobs" | sed -n "$((i+1))p")
-              step=$(echo "$steps" | sed -n "$((i+1))p")
-              duration=$(echo "$durations" | sed -n "$((i+1))p")
-              echo "| $job | $step | $duration |"
-            done
-          } >> $GITHUB_STEP_SUMMARY
+  #     - name: Create a table with job durations and set as output
+  #       id: create_table
+  #       run: |
+  #         {
+  #           echo ${{ needs.docker_build_scan_push.outputs.matrix_job_names }}
+  #           echo "| Job | Step | Duration |"
+  #           echo "| --- | --- | --- |"
+  #           jobs=$(echo '${{ steps.calculate_durations.outputs.jobs }}' | jq -r '.[]')
+  #           steps=$(echo '${{ steps.calculate_durations.outputs.steps }}' | jq -r '.[]')
+  #           durations=$(echo '${{ steps.calculate_durations.outputs.durations }}' | jq -r '.[]')
+  #           for i in $(seq 0 $(($(echo "$jobs" | wc -l) - 1))); do
+  #             job=$(echo "$jobs" | sed -n "$((i+1))p")
+  #             step=$(echo "$steps" | sed -n "$((i+1))p")
+  #             duration=$(echo "$durations" | sed -n "$((i+1))p")
+  #             echo "| $job | $step | $duration |"
+  #           done
+  #         } >> $GITHUB_STEP_SUMMARY
 
-      - name: workflow has ended without issue
-        run: |
-          if ${{ contains(needs.run_behat_suite.result, 'success') && contains(needs.ecr_scan_results.result, 'success') && contains(needs.terraform_preproduction_plan_environment.result, 'success') }}; then
-            echo "${{ needs.workflow_variables.outputs.safe_branch_name }} PR environment tested, built and deployed"
-            echo "Tag Used: ${{ needs.workflow_variables.outputs.safe_branch_name }}-${{ needs.workflow_variables.outputs.short_sha }}"
-            echo "URL: https://${{ needs.workflow_variables.outputs.workspace_name }}.use-lasting-power-of-attorney.service.gov.uk"
-            exit 0
-          elif [[ ${{ needs.workflow_variables.outputs.specific_path }} = 'docs' ]]; then
-            echo 'Ending docs workflow'
-            exit 0
-          else
-            echo "Previous jobs in pipeline failed."
-            exit 1
-          fi
+  #     - name: workflow has ended without issue
+  #       run: |
+  #         if ${{ contains(needs.run_behat_suite.result, 'success') && contains(needs.ecr_scan_results.result, 'success') && contains(needs.terraform_preproduction_plan_environment.result, 'success') }}; then
+  #           echo "${{ needs.workflow_variables.outputs.safe_branch_name }} PR environment tested, built and deployed"
+  #           echo "Tag Used: ${{ needs.workflow_variables.outputs.safe_branch_name }}-${{ needs.workflow_variables.outputs.short_sha }}"
+  #           echo "URL: https://${{ needs.workflow_variables.outputs.workspace_name }}.use-lasting-power-of-attorney.service.gov.uk"
+  #           exit 0
+  #         elif [[ ${{ needs.workflow_variables.outputs.specific_path }} = 'docs' ]]; then
+  #           echo 'Ending docs workflow'
+  #           exit 0
+  #         else
+  #           echo "Previous jobs in pipeline failed."
+  #           exit 1
+  #         fi
 
-    if: always()
+  #   if: always()
