UML-3684: prevent failed PR workflow from passing checks

diff --git a/.github/workflows/pull-request-path.yml b/.github/workflows/pull-request-path.yml
--- a/.github/workflows/pull-request-path.yml
+++ b/.github/workflows/pull-request-path.yml
@@ -293,10 +293,10 @@ jobs:
     runs-on: ubuntu-latest
     needs:
       - ecr_scan_results
-      - slack_notify
       - workflow_variables
       - update_documentation
       - docker_build_scan_push
+      - run_behat_suite
     steps:
       - uses: actions/checkout@v4
 
@@ -331,17 +331,16 @@ jobs:
 
       - name: workflow has ended without issue
         run: |
-          if [[ ${{ needs.workflow_variables.outputs.specific_path }} = 'docs' ]]
-          then
-            echo 'Ending docs workflow'
-          else
+          if ${{ contains(needs.run_behat_suite.result, 'success') && contains(needs.ecr_scan_results.result, 'success') }}; then
             echo "${{ needs.workflow_variables.outputs.safe_branch_name }} PR environment tested, built and deployed"
             echo "Tag Used: ${{ needs.workflow_variables.outputs.safe_branch_name }}-${{ needs.workflow_variables.outputs.short_sha }}"
             echo "URL: https://${{ needs.workflow_variables.outputs.workspace_name }}.use-lasting-power-of-attorney.service.gov.uk"
+            exit 0
+          elif [[ ${{ needs.workflow_variables.outputs.specific_path }} = 'docs' ]]; then
+            echo 'Ending docs workflow'
+          else
+            echo "Previous jobs in pipeline failed."
+            exit 1
           fi
-    if: |
-      always() &&
-      ((needs.ecr_scan_results.result == 'success' || needs.ecr_scan_results.result == 'skipped') &&
-      needs.slack_notify.result == 'success' &&
-      needs.workflow_variables.result == 'success') ||
-      needs.update_documentation.result == 'success'
+
+    if: always()
